melting_proto/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts do
    post "/like", to: "likes#like_toggle"
    resources :comments, except: [:index, :new, :show] do
        member do
          get :reply
      end
    end
  end
  resources :follows, only: [:create, :destroy]

  devise_for :users
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

melting_proto/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy
end

melting_proto/app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

melting_proto/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

melting_proto/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  #CarrierWave
  mount_uploader :image, PostImageUploader

end

melting_proto/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  # 나를 팔로우 한 유저 가져오기
  has_many :follower_relations, foreign_key: "followed_id", class_name: "Follow"
  has_many :followers, through: :follower_relations, source: :follower
  # 내가 팔로잉 한 유저 가져오기
  has_many :following_relations, foreign_key: "follower_id", class_name: "Follow"
  has_many :followings, through: :following_relations, source: :followed
  # CarrierWave
  mount_uploader :avatar, AvatarUploader

  # Check like
  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end
end

melting_proto/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!
before_action :set_commentable
before_action :set_comment, only: [ :reply, :edit, :update, :destroy ]

  def reply
    @reply = @commentable.comments.build(parent: @comment)
  end

  def create
   @comment = @commentable.comments.new(comment_params)
   @comment.user = current_user
   respond_to do |format|
     if @comment.save
       format.html { redirect_to @commentable, notice: "Comment was successfully created."}
       format.json { render json: @comment }
       format.js
     else
       format.html { render :back, notice: "Comment was not created." }
       format.json { render json: @comment.errors }
       format.js
     end
   end
  end

  def edit
  end

  def update
    respond_to do |format|
     if @comment.update(comment_params)
       format.html { redirect_to @commentable, notice: "Comment was successfully updated."}
       format.json { render json: @comment }
       format.js
     else
       format.html { render :back, notice: "Comment was not updated." }
       format.json { render json: @comment.errors }
       format.js
     end
   end
  end

  def destroy
    @comment.destroy if @comment.errors.empty?
     respond_to do |format|
       format.html { redirect_to @commentable, notice: "Comments was successfully destroyed."}
       format.json { head :no_content }
       format.js
     end
  end

  private

  def set_commentable
    resource, id = request.path.split('/')[1,2]
    @commentable = resource.singularize.classify.constantize.find(id)
  end

  def set_comment
    begin
      @comment = @commentable.comments.find(params[:id])
    rescue => e
      logger.error "#{e.class.name} : #{e.message}"
      @comment = @commentable.comments.build
      @comment.errors.add(:base, :recordnotfound, message: "That record doesn't exist. Maybe, it is already destroyed.")
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :parent_id)
  end
end

melting_proto/app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    Follow.create(followed_id: params[:followed_id], follower_id: current_user.id)
    redirect_back fallback_location: root_path
  end

  def destroy
    Follow.find_by(followed_id: params[:id], follower_id: current_user.id).destroy
    redirect_back fallback_location: root_path
  end
end

melting_proto/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def like_toggle
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])

    if like.nil?
      Like.create(user_id: current_user.id, post_id: params[:post_id])
    else
      like.destroy
    end
    redirect_back fallback_location: root_path
  end
end

melting_proto/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    # @post = Post.new(user_id: current_user.id,
    #                  content: params[:content],
    #                  image: params[:image])
    # Amended Code
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :title, :content)
    end
end

melting_proto/app/helpers/comments_helper.rb
module CommentsHelper
end

melting_proto/app/helpers/follows_helper.rb
module FollowsHelper
end

melting_proto/app/helpers/likes_helper.rb
module LikesHelper
end

melting_proto/app/views/comments/_comment.html.erb
<li id="comment_<%= comment.id %>" class="comment">
  <div class="comment-content">
    <%= comment.content %>
  </div>
  <div class="comment-info">
    <small>-
      <!--Amended Code-->
      <%= comment.user.email %> &bull;
      <%= localize(comment.created_at, format: :long) %> &bull;
      <%= link_to "Edit", edit_polymorphic_path([comment.commentable, comment]), class: 'edit-comment-link', remote: true  %> &bull;
      <%= link_to "Destroy", [comment.commentable, comment], method: :delete, class: 'delete-comment-link', data:{confirm:"Are your sure?"}, remote: true %> &bull;
      <%= link_to "Reply", polymorphic_path([:reply, comment.commentable, comment]), class: 'reply-comment-link', remote: true  %>
    </small>
  </div>
  <% if comment.replies.any? %>
    <ul>
      <%= render comment.replies %>
    </ul>
  <% end %>
</li>

melting_proto/app/views/comments/_form.html.erb
<div class="comment-form">
  <%= simple_form_for [comment.commentable, comment], remote: true do | f | %>
    <%= f.hidden_field :parent_id %>
    <%= f.input :content, label: false, placeholder: (f.object.parent_id.nil? ? 'Share your idea.' : 'Leave your reply.'), input_html: { rows: 5, data:{ 'comment-id': (comment.persisted? ? comment.id : 'new') }} %>
    <span id="comment_<%= comment.persisted? ? comment.id : 'new' %>"></span>
    <%= link_to "Cancel", "#", 'data-reply': comment.parent_id.present?, class: 'cancel-comment-link btn btn-primary btn-sm float-xs-right ml-1' if comment.persisted? or comment.parent %>
    <%= f.submit class: 'btn btn-primary btn-sm float-xs-right' %>
    <div class="clearfix"></div>
  <% end %>
</div>

melting_proto/app/views/comments/_widget.html.erb
<div id="comments-widget-of-commentable-<%= commentable.id %>" class="comments-widget">
  <h5 class="comments-header">
    Comments
    <small id="comments-count-of-commentable-<%= commentable.id %>">
      <%= commentable.comments.size %>
    </small>
  </h5>
  <ul class="comments-list">
    <%= render commentable.comments.where(parent: nil) %>
  </ul>
  <!-- comment-form -->
  <%= render "comments/form", comment: commentable.comments.build  %>
</div>

melting_proto/app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

melting_proto/app/views/comments/create.js.erb
// create.js.erb (CommentsController#create)
<% if @comment.parent %>
  $comment_parent = $("#comment_<%= @comment.parent.id %> > ul");
  if(!$comment_parent.length){
    $("#comment_<%= @comment.parent.id %>").append("<ul></ul>");
    $comment_parent = $("#comment_<%= @comment.parent.id %> > ul");
  }
  $comment_form = $("#comment_<%= @comment.parent.id %> .comment-form form");
<% else %>
  $comment_parent = $("#comments-widget-of-commentable-<%= @commentable.id %> .comments-list");
  $comment_form = $("#comments-widget-of-commentable-<%= @commentable.id %> .comment-form form");
<% end %>

$comments_count = $("#comments-count-of-commentable-<%= @commentable.id %>");
<% if @comment.errors.empty?  # if no errors on creating a comment... %>
  //Add append comment function through Ajax
  $comment_parent.append("<%=j render @comment %>").find('li').last();
  $comment_form[0].reset();
  <% if @comment.parent %>
    $comment_form.remove();
    // console.log("start");
    $comment = $("#comment_<%= @comment.parent.id %>")
    // console.log("end");
    $restore_link = $comment.find('a.delete-comment-link')[0]
    $reply_link = $comment.find('a.reply-comment-link')[0]
    $reply_link.href = $restore_link.href + "/reply"
  <% end %>
  $("#comment_new_chars_counter").html("Remaining : 255");
<% else # if some errors occurs on creating a comment... %>
  $comment_form.before("<div class='alert alert-warning alert-dismissible fade in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= @comment.errors.full_messages.join('') %></div>").prev().delay(1500).slideUp();
<% end %>

melting_proto/app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

melting_proto/app/views/comments/destroy.js.erb
$comments_count = $("#comments-count-of-commentable-<%= @commentable.id %>");
<% if @comment.errors.empty? %>
  $comments_count.html("<%= @commentable.comments.size %>");
  $("#comment_<%= @comment.id %>").slideUp('fast');
<% else %>
  $("#comments-widget-of-commentable-<%= @commentable.id %> .comments-header").after("<div class='alert alert-warning alert-dismissible fade in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= @comment.errors.full_messages.join('') %></div>").next().delay(1500).slideUp('fast');
<% end %>

melting_proto/app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

melting_proto/app/views/comments/edit.js.erb
// edit.js.erb
<% if @comment.errors.empty? %>
  $("#comment_<%= @comment.id %> > .comment-info .edit-comment-link").removeAttr("href");
  $("#comment_<%= @comment.id %> > .comment-info").after("<%=j render('comments/form', comment: @comment) %>");
<% else %>
  $("#comments-widget-of-commentable-<%= @commentable.id %> .comments-header").after("<div class='alert alert-warning alert-dismissible fade in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= @comment.errors.full_messages.join('') %></div>").next().delay(1500).slideUp('fast');
<% end %>

// On editing a comment, call to counter of comment.
$("#comment_<%= @comment.id %> form textarea").trigger('keyup');

melting_proto/app/views/comments/reply.html.erb
<h1>Comments#reply</h1>
<p>Find me in app/views/comments/reply.html.erb</p>

melting_proto/app/views/comments/reply.js.erb
// reply.js.erb
<% if @comment.errors.empty? %>
  $("#comment_<%= @comment.id %> > .comment-info .reply-comment-link").removeAttr("href");
  $("#comment_<%= @comment.id %> > .comment-info").after("<%=j render('comments/form', comment: @reply) %>");
<% else %>
  $("#comments-widget-of-commentable-<%= @commentable.id %> .comments-header").after("<div class='alert alert-warning alert-dismissible fade in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= @comment.errors.full_messages.join('') %></div>").next().delay(1500).slideUp('fast');
<% end %>

melting_proto/app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

melting_proto/app/views/comments/update.js.erb
// update.js.erb (CommentsController#create)
$comment_form = $("#comment_<%= @comment.id %> .comment-form form");
$comment = $("#comment_<%= @comment.id %>");
<% if @comment.errors.empty?  # if no erros on creating a comment... %>
  $comment.html("<%=j render @comment %>").find('li').last().effect("highlight", {}, 1000);
  $comment_form[0].remove();
<% else # if some errors occurs on creating a comment... %>
  $comment_form.before("<div class='alert alert-warning alert-dismissible fade in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= @comment.errors.full_messages.join('') %></div>").prev().delay(1500).slideUp();
<% end %>

melting_proto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeltingProto</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="assets/css/main.css" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render '/posts/navbar' %>
    <%= yield %>
    <%= render '/posts/footer' %>

    <!-- Scripts -->
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/skel.min.js"></script>
    <script src="assets/js/util.js"></script>
    <script src="assets/js/main.js"></script>
  </body>
</html>

melting_proto/app/views/posts/_follow.html.erb
<!-- follow function -->
<% if user_signed_in? && current_user != @post.user %>
  <% if current_user.followings.include?(@post.user) %>
    <%= form_tag follow_path(@post.user.id), method: :delete, class: "right" do %>
      <button class="btn">Unfollow</button>
    <% end %>
  <% else %>
    <%= form_tag follows_path, method: :post, class: "right" do %>
      <input type="hidden" name="followed_id" value="<%=@post.user.id%>">
      <button class="btn">Follow</button>
    <% end %>
  <% end %>
<% end %>

melting_proto/app/views/posts/_footer.html.erb
<!-- Footer -->
  <section id="footer">
    <ul class="icons">
      <li><a href="#" class="fa-twitter"><span class="label">Twitter</span></a></li>
      <li><a href="#" class="fa-facebook"><span class="label">Facebook</span></a></li>
      <li><a href="#" class="fa-instagram"><span class="label">Instagram</span></a></li>
      <li><a href="#" class="fa-rss"><span class="label">RSS</span></a></li>
      <li><a href="#" class="fa-envelope"><span class="label">Email</span></a></li>
    </ul>
    <p class="copyright">&copy; Melting</p>
  </section>

melting_proto/app/views/posts/_form.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Melting Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="assets/css/main.css" />
  </head>

  <body class="">
    <%= simple_form_for(@post) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.association :user %>
        <%= f.input :title %>
        <%= f.input :content %>
        <%= file_field_tag :image %>
      </div>

      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    <% end %>

  </body>
</html>

melting_proto/app/views/posts/_like.html.erb
<div>
  - <%= @post.likes.size %> degrees
  <!-- like button-->
  <% if current_user.is_like?(@post) %>
     <%= link_to "Cancel", post_like_path(@post), method: "post" %>
  <% else %>
    <%= link_to "Freeze", post_like_path(@post), method: "post" %>
  <% end %>
</div>

melting_proto/app/views/posts/_navbar.html.erb
<!-- Header -->
  <header id="header">
    <h1><a href="#">Melting</a></h1>
    <nav class="links">
      <ul>
        <% unless current_page?(root_path) %>
          <li><%= link_to 'Home', root_path%></li>
        <% end %>
        <% if user_signed_in? %>
          <li><%= link_to "Profile", edit_user_registration_path%></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, data: {confirm:"Are you sure?"}%></li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path unless current_page?(new_user_session_path) %></li>
          <li><%= link_to "Sign up", new_user_registration_path unless current_page?(new_user_registration_path) %></li>
        <% end %>
      </ul>
    </nav>
    <nav class="main">
      <ul>
        <li class="search">
          <a class="fa-search" href="#search">Search</a>
          <form id="search" method="get" action="#">
            <input type="text" name="query" placeholder="Search" />
          </form>
        </li>
        <li class="menu">
          <a class="fa-bars" href="#menu">Menu</a>
        </li>
      </ul>
    </nav>
  </header>

<!-- Menu -->
  <section id="menu">

    <!-- Search -->
      <section>
        <form class="search" method="get" action="#">
          <input type="text" name="query" placeholder="Search" />
        </form>
      </section>

    <!-- Links -->
      <section>
        <ul class="links">
          <li>
            <a href="posts/index">
              <h3>NewsFeed</h3>
            </a>
          </li>
          <li>
            <a href="#">
              <h3>Messenger</h3>
            </a>
          </li>
        </ul>
      </section>

    <!-- Actions -->
      <section>
        <ul class="actions vertical">
          <li><a href="posts/new" class="button big fit">New Post</a></li>

        </ul>
      </section>

  </section>

melting_proto/app/views/posts/_posts.html.erb
<!-- Post -->
  <article class="post">
    <header>
      <% @posts.each do |post| %>
      <div class="title">
        <h2><a href="#"><%= post.title %></a></h2>
      </div>
      <div class="meta">
        <time class="published"><%=post.created_at%></time>
        <a href="#" class="author"><span class="name"><%= post.user.email %></span><img src="images/avatar.jpg" alt="" /></a>
      </div>
    </header>
    <!--CarrierWave images  -->
    <a href="#" class="image featured"><img src="images/pic01.jpg" alt="" /></a>
    <%= post.content %>
    <footer>
      <ul class="actions">
        <li><a href="/posts/show/#{post.id}" class="button big">Continue Reading</a></li>
      </ul>
      <ul class="stats">
      <% if user_signed_in? && current_user == post.user %>
        <li><%= link_to 'Edit', edit_post_path(post) %></li>
        <li><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        <li><%= post.likes.size%></li>
        <% end %>
      </ul>
    </footer>
  </article>
  <% end %>

melting_proto/app/views/posts/_user_info.html.erb
<div class="my_info">
  <% if user_signed_in?%>
    <h3>my info</h3>
    <p>email : <%= current_user.email%> | posts count: <%= current_user.posts.size %></p>
    <p>follower: <%= current_user.followers.length %> | following: <%= current_user.followings.length %></p>
  <% else %>
    <p>Welcome to melting</p>
  <% end %>
</div>

melting_proto/app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Melting Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="assets/css/main.css" />
  </head>

  <body>
    <p id="notice"><%= notice %></p>
    <!-- Wrapper -->
			<div id="wrapper">

    <!-- Main -->
      <div id="main">

        <!-- Post -->
        <% @posts.each do |post| %>
          <article class="post">
            <header>
              <div class="title">
                <!--title -->
                <h2><a href="#"><%= post.title %></a></h2>
                <!--태그 넣을 예정  -->
                <%#= post.tags %>
              </div>
              <div class="meta">
                <time class="published"><%=post.created_at%></time>
                <a href="#" class="author"><span class="name"><%= post.user.email %></span><img src="images/avatar.jpg" alt="" /></a>
              </div>
            </header>
            <span class="image featured"><img src="images/pic01.jpg" alt="" /></span>
            <!--contents  -->
            <%= post.content %>
            <footer>
              <ul class="stats">
                <li><%= link_to 'Show more', post %></li>
                <li><a href="#" class="icon fa-heart"><%=post.likes.size %></a></li>
                <li><a href="#" class="icon fa-comment"><%=post.comments.size %></a></li>
              </ul>
            </footer>
          </article>
        <% end %>
      </div>
    </div>
  </body>
</html>

melting_proto/app/views/posts/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Melting Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="assets/css/main.css" />
  </head>

  <body>
    <p id="notice"><%= notice %></p>
    <!-- Wrapper -->
			<div id="wrapper">

    <!-- Main -->
      <div id="main">
        <!-- Post -->
          <article class="post">
            <header>
            <%= render 'follow', post: @post %>
              <div class="title">
                <!--title -->
                <h2><a href="#"><%= @post.title %></a></h2>
                <!--태그 넣을 예정  -->
                <%#= post.tags %>
              </div>
              <div class="meta">
                <time class="published"><%=@post.created_at%></time>
                <a href="#" class="author"><span class="name"><%= @post.user.email %></span><img src="images/avatar.jpg" alt="" /></a>
              </div>
            </header>
            <span class="image featured"><img src="images/pic01.jpg" alt="" /></span>
            <!--contents  -->
            <%= @post.content %>
            <%= render "comments/widget", commentable: @post %>
            <footer>
              <ul class="stats">
                <li><%= link_to 'Back', posts_path %></li>
                <%if current_user.id == @post.user_id %>
                  <li><%= link_to 'Edit', edit_post_path(@post) %></li>
                  <li><%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                <% end %>
                <li><a href="#" class="icon fa-heart"><%=@post.likes.size %></a></li>
                <li><a href="#" class="icon fa-comment"><%=@post.comments.size %></a></li>
              </ul>
            </footer>
          </article>
      </div>
    </div>
  </body>
</html>